### ISSUE TITLE
QUESTION: Is support of the full submission API part of the plan?

### ISSUE THREAD

**Issue by ddurham2** [novacode-nl/python-formio-data#22]
Is this project intending to eventually wrap the submission API?  Was looking for a package on pypi. Thanks

**Comment by bobslee** [comment]
Do you mean the https://form.io server API ?
Because that's won't be the case (covering) here.

This project only covers the Form.io JSON data, which of course can be obtained in any way you need:
- parsing into usable Python objects
- Updating (writing) Form.io data back - usually the value of component.

**Comment by bobslee** [comment]
This library is already heavily used in my Odoo Forms modules, which serves as an on-premise platform for Formio forms.

(Integrated in Odoo, open source ERP, business software).

https://apps.odoo.com/apps/modules/14.0/formio/

https://apps.odoo.com/apps/modules/browse?search=formio

**Comment by ddurham2** [comment]
Well, I was just originally looking for a python module that wraps the formio api documented here: https://apidocs.form.io/#9fe90026-dd4b-a344-62e9-c7a67f0ebbb7

One might want to fetch or modify some form submissions from python. Obviously, one can make the REST calls themselves, but a lib could make it a bit more convenient.

I saw that your project was first published recently, and didn't know if it was aiming to be a full python implementation of all the API.  Maybe not.

**Comment by bobslee** [comment]
Hi @ddurham2 , indeed this project doesn't focus on the REST API, which is a different responsibility. 
Won't be hard to implement REST tough and you can use this library for the data processing.

Has your question been answered? Please close the issue.

**Comment by ddurham2** [comment]
Thank You
